### PR TITLE
Format code

### PR DESCRIPTION
**Pull request by Murmele**
format code according to Google standard: clang-format --style=Google -dump-config > .clangformat
Add ci to check if code format is correctly

When I run the Google style with clang-format, it seems a lot of files get touched

### CODE REVIEW

**Comment by ihedvall** [comment]
It's better to wait with the formatting features until we have a stable code base.

**Comment by Murmele** [comment]
Ok I will let it open.

**Comment by ihedvall** [comment]
1. I have tested the clang format. It is working for most C++ files but not for wxWidgets related C++ files.
2. Should the the format file be named '.clang-format' or '.clangformat' ? 
3. Is it possible to separate the actual build from the format check by two yaml files?
4. The bash script is somewhat complicated.

**Comment by ihedvall** [comment]
Is it possible to skip the cmake file formatting?

**Comment by Murmele** [comment]
I changed it to format only the source code and no cmake

**Comment by Murmele** [comment]
You can set in the settings of github that merge pull request only allowed when CI build is running through.
I will check out why it failed

**Comment by Murmele** [comment]
I have to check why it crashes after formatting the code

**Comment by ihedvall** [comment]
I have added the clang format to the utillib project so the CLION uses its formatting rules. I notice that is changes the order of include files which most likely causing some build problems.

I can do the same on the mdflib project but this will generate a difficult merge.

**Comment by Murmele** [comment]
> 

We can also turn off resorting includes? Why it is getting a difficult merge? If you are doing it on master it should bring additional issues?

**Comment by ihedvall** [comment]
Doing the clang format in the editor, then I can compile before pushing. This solves the initial checkin. Setting up the editor to automatic reformat files at save minimizes the risk of further clang format issues.

Do you want me to do the intial clang-format checkin on master?

**Comment by Murmele** [comment]
> Doing the clang format in the editor, then I can compile before pushing. This solves the initial checkin. Setting up the editor to automatic reformat files at save minimizes the risk of further clang format issues.
> 
> Do you want me to do the intial clang-format checkin on master?

yes you can do. I don't have anything against. currently I don't have changed source code so I don't have to do any merge requests

**Comment by ihedvall** [comment]
The TestInstall fails in the build due to expat library missing. I'm lost in the cmake-nested-cmake. Do you have a solution of mdflib dependency of expat library?

**Comment by Murmele** [comment]
> The TestInstall fails in the build due to expat library missing. I'm lost in the cmake-nested-cmake. Do you have a solution of mdflib dependency of expat library?

I will check out. I think in the Test we should not link to expat, because it is not directly needed. It should be linked in mdflib. I will check it out.

**Comment by Murmele** [comment]
there is not find_package() for expat anymore. So you would like to force to use the downloaded version?

**Comment by Murmele** [comment]
EXPAT_LIBRARIES gets also not populated

**Comment by ihedvall** [comment]
I think this pull request is out-dated.

**Pull request closed without merging**
