### PR TITLE
Fix Build

### PR DESCRIPTION
**Pull request by Murmele**
add expat as requirement

### CODE REVIEW

**Review by ihedvall — APPROVED** [review]

**Comment by Murmele** [comment]
ok now it did not fix

**Comment by ihedvall** [comment]
Both the libexpat.a and libmdf.a are installed into the .../lib/* install directory. If it finds the mdf library it should also find the expat library. Maybe find expat before finding mdf should solve the problem?

**Comment by ihedvall** [comment]
Sorry about the interrupt on MDF library. I have been working with an delivery regarding CAN logger MDF files. I have made a DBC library with message parsing at least for some of the CAN protocols (NMEA 2000 and raw CAN). It is extended signals (more than 8 bytes) that require knowledge about the protocol in use for the CAN bus.

I don't know the current status regarding your usage of the mdflib. Please let me know.

**Comment by Murmele** [comment]
Hi @ihedvall currently I was not able to finish the work for the mdflib, because of missing c++20 support on our side
Currently I am implementing vector blf because there is a library able to use c++11. There I had also to parse a dbc file. I used the following library there: https://github.com/LinuxDevon/dbc_parser_cpp

**Comment by ihedvall** [comment]
It isn’t impossible to fix the mdflib so it works with C++ 11 compilers. Please let me know if I should do this?

 

Regarding DBC files, Vector have added an extended multiplex signal definition on top of the normal multiplexed signal. You may find the ParseMessage() function in ihedvall/dbclib/src/network.cpp, message.cpp and signal.cpp files useful.

 

You can reach me on email ***@***.*** if you have any problem.

Best regards 

Ingemar Hedvall

 

 

Från: Murmele ***@***.***> 
Skickat: den 11 januari 2023 11:30
Till: ihedvall/mdflib ***@***.***>
Kopia: Ingemar Hedvall ***@***.***>; Mention ***@***.***>
Ämne: Re: [ihedvall/mdflib] Fix Build (PR #12)

 

Hi @ihedvall <https://github.com/ihedvall>  currently I was not able to finish the work for the mdflib, because of missing c++20 support on our side
Currently I am implementing vector blf because there is a library able to use c++11. There I had also to parse a dbc file. I used the following library there: https://github.com/LinuxDevon/dbc_parser_cpp

**Comment by Murmele** [comment]
If you have the time to do it would be nice. I will finish the blf import for labplot. Implementing mdf should be then pretty straight forward and quite simple.

Your mail address is not visible. You can find my mail address here in this file: https://github.com/KDE/labplot/blob/master/src/backend/datasources/filters/SpiceFilter.h

**Comment by Murmele** [comment]
@ihedvall From next version of labplot on, we can also support C++17. So you don't have to port down to C++11

**Comment by Murmele** [comment]
> 

I had a big issue with my parsing of the data regarding little endian and big endian. So in the next weeks I will try to get the dbclib ready for using in labplot

**Pull request closed without merging**
