### PR TITLE
export functions to build shard library and use vcpkg to manage dependennces

### PR DESCRIPTION
**Pull request by Simplxss**
Currently in progress, don't maege it!
Suggestions welcome.

#29 #30

### CODE REVIEW

**Review by ihedvall — COMMENTED** [review]
I tried to use cmake for C++/CLI projects earlier and it failed. Works for C# but not C++/CLI why the .NET project is in a separate vcproj instead of cmake. Does thiis actually build?

**Comment by Simplxss** [comment]
CLR will enable only when complier is MSVC.
There is one [property](https://cmake.org/cmake/help/latest/prop_tgt/COMMON_LANGUAGE_RUNTIME.html) to enable it.
`set_target_properties(mdflibrary PROPERTIES COMMON_LANGUAGE_RUNTIME "")`
When built by gcc or other compilers, only pure C functions will be exported.
All exported functions are in `MdfExport.h/cpp`.

**Comment by Simplxss** [comment]
Moreover, I have tested building in windows and ubuntu(wsl), it wsorks well.(except install)
I don't know how to change the path, the true path is `include/mdflibrary/MdfExport.h`.
Why cmake append `mdflibrary/` in front of it?
```sh
CMake Error at mdflibrary/cmake_install.cmake:65 (file):
  file INSTALL cannot find
  "/home/runner/work/mdflib/mdflib/mdflibrary/include/mdflibrary/MdfExport.h":
  No such file or directory.
```

**Comment by Simplxss** [comment]
Building in Linux and Windows is fixed, macos need replace the functions in mdflib\src\platform.h/cpp to fix.
Do you have time to fix it?

**Comment by ihedvall** [comment]
The XCode C compiler (XSI vs GNU) need some ifdefs. I don't have a working MacOS environment yet. Will take some days.

**Review by ihedvall — CHANGES_REQUESTED** [review]
The debug builds (actual cmake configure) fails with the below cmake error. Something about mixing /clr and /rtc1 compile flags.

CMake Warning in mdflibrary/CMakeLists.txt:
  For the target "mdflibrary" the /clr compiler flag was added manually.  Set
  usage of C++/CLI by setting COMMON_LANGUAGE_RUNTIME target property.


-- Generating done (0.1s)
-- Build files have been written to: D:/projects/mdflib_vcpkg/build/msvc

Cannot get compiler information:
	Compiler exited with error code 2: "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe" @C:\Users\ihedv\AppData\Local\Temp\response-file16127765658546383826 C:\Users\ihedv\AppData\Local\Temp\compiler-file12750811594760792576 | @response-file16127765658546383826=/TP /Dmdflibrary_EXPORTS /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -std:c++17 -MDd /EHa /clr /Be /Bd /EP /w /wd4067
	Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32532
	for Microsoft (R) .NET Framework version 4.08.9167.0
	Copyright (C) Microsoft Corporation.  All rights reserved.
	
	all:
		@cd D:\projects\mdflib_vcpkg\build\msvc\mdflibrary
		@set INCLUDE=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um
		@set LIB=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64
		@set LIBPATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0;C:\Windows\Microsoft.NET\Framework64\v4.0.30319
		@set CL=
		@set _CL_=
		@set LINK=
		C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe @<< C:\Users\ihedv\AppData\Local\Temp\compiler-file12750811594760792576
	/TP /Dmdflibrary_EXPORTS /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -std:c++17 -MDd /EHa /clr /Be /Bd /EP /w /wd4067<<
	
	cl /TP /Dmdflibrary_EXPORTS /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -std:c++17 -MDd /EHa /clr /Be /Bd /EP /w /wd4067
	cl : Command line warning D9025 : overriding '/EHs' with '/EHa'
	cl : Command line error D8016 : '/RTC1' and '/clr' command-line options are incompatible

**Comment by ihedvall** [comment]
It's not possible to build the mdfview(er) or mdf_test executable. Using CLion editor.

**Comment by ihedvall** [comment]
FYI
Some of the CMAKE_TOOLCHAIN_FILE paths are fixed, not using the VCPKG_ROOT environment varaible. I patched them temporary.

**Comment by Simplxss** [comment]
I have added CMakeUserPresets.json to .gitignore, but it didn't take effect... You should config it according to your own environment.

**Comment by ihedvall** [comment]
The gitignore trouble is that the *user.json already is in the repository so you need to manually delete it in the repository.

**Comment by Simplxss** [comment]
Can you provide your cmake version, visual studio verison. And do you install C++/CLI Support in vs installer.
In addition, cmake build command and full log.

**Comment by ihedvall** [comment]
Tried with Rider (C#) editor. It freaks out as it uses the vcproj/sln not cmake solution. Moving/renaming directories causing problems. Gussing that VS studio have the same problem with the solution file.

Another new feature is that the mdf_test do build with Ninja but when running no test are found. Guessing it's just some cmake "enable test" magic missing.

**Comment by Simplxss** [comment]
Can you try to build mdflibrary with generator "Visual Studio 17 2022", the config defined in CMakeUserPresets.json.(remember to change the vcpkg director)

**Comment by ihedvall** [comment]
All C++ projects uses CMake solution and CLion as editor in Windows/Linux/MacOs. Well the last one is in progress.
CMake 3.26.4
VS2022 Community 17.0 (window). 
GUI through WxWidgets.

All C++/CLI and C# applications uses Visual Studio (Windows Only) or JetBrains Rider (All OS) and SLN solution files (not cmake).
VS2022 as above.
GUI through Avalonia and .NET Core.
The C++/CLI interfaces are not for new designs as it doesn't work well with .NET core and Linux. Instead is the gRPC used.

**Comment by Simplxss** [comment]
Can you try to build with config msvc-multi-vcpkg?

**Comment by ihedvall** [comment]
I have tested with just adding the CMAKE_TOOLCHAIN_FILE and with several modifications, almost everything works but the following doesn't work or is a no go.

1. The project now require VCPKG to build.
2. Many source files have moved to other directories of no reason.
3. The C++/CLI mdflibrary doesn't load in debug (but in release?). Excluding the .NET from the CMake will solve this problem.
4. Many directories has changed name without any reason.
5. The executables are dependent on Util Lib but it seems that the files has been copied instead.
6. The JetBrain Rider cannot load the .NET mdflibrary. This mainly due to changed libraries.

I fixed some minor problem with unit test (found no tests problem)

**Comment by Simplxss** [comment]
I will re-add the sln project for C++/CLI as an optional, and add flag to control the cmake project. Besides, It is okey to build but there are [some bugs of Visual Studio](https://developercommunity.visualstudio.com/t/Toolset-v143version1436176-cannot-f/10431978) that also exist in the environment of github action making it fall to build.
Some source files are moved to other directory to make it clear and easy to identify the funtion of it(for example ./src -> ./mdflib/src, static library)
Vcpkg is more easy to building dependences. You just need to add "CMAKE_TOOLCHAIN_FILE": "[vcpkg root]/scripts/buildsystems/vcpkg.cmake" to cmake command and all things will be done. If you think its better to manually download and build all of dependence, I will add it as an optional.
I use VS/VSCode to coding c++, and not very familiar with CLion, if you can't use cmake to build mdflibrary, you can try to turn MDF_BUILD_SHARED_LIB OFF to avoid loading it.

**Review by ihedvall — APPROVED** [review]
The cmake require VCPKG but project that includes this library uses a component disc/directory instead. Merge this and I will add support for component disc/directory later.

**Comment by Simplxss** [comment]
VCPKG should be an option to install packages now.
In addition, build on windows will be disabled because MSVC 19.35.32217.1 does not support condition_variable in clr

**Comment by Simplxss** [comment]
Another question. The current filepath uses ANSI coding. It will cause error when containing not ASCII words. Is it okey to change it to utf8 coding?

**Comment by ihedvall** [comment]
It's OK to change it to UTF8 coding. Mdflib should not be compiled with /clr option?

**Comment by Simplxss** [comment]
Mdflib won't be compiled with /clr option, but Mdflibrary will. Maybe I can disable building shared library in workflow? I will try it.

**Comment by Simplxss** [comment]
Notice that presets that don't use vcpkg should be added.

**Pull request merged**
